# Generated by Django 3.1.3 on 2020-11-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0004_auto_20201110_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.jpeg', upload_to='profilepic/'),
        ),
    ]
