# Generated by Django 3.1.3 on 2020-11-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0005_auto_20201110_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
