# Generated by Django 3.1.3 on 2020-11-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0006_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
