# Generated by Django 3.1.3 on 2020-11-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0008_auto_20201110_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=40),
        ),
    ]
