# Generated by Django 3.1.3 on 2020-11-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0011_auto_20201112_0923'),
        ('dressup', '0011_photo'),
    ]

    operations = [
    ]
