# Generated by Django 3.1.3 on 2020-11-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0012_merge_20201112_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Ladies', 'Ladies'), ('Kids', 'Kids')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
