# Generated by Django 3.1.3 on 2020-11-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0014_auto_20201117_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='profile',
            new_name='username',
        ),
    ]
