# Generated by Django 3.1.3 on 2020-11-18 09:24

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0019_auto_20201117_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
