# Generated by Django 3.1.3 on 2020-11-18 09:33

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0020_auto_20201118_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='productpic/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dressup.profile'),
        ),
    ]
