# Generated by Django 3.1.3 on 2020-11-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0021_auto_20201118_1233'),
        ('dressup', '0014_auto_20201117_0933'),
    ]

    operations = [
    ]
