# Generated by Django 3.1.3 on 2020-11-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0023_post'),
        ('dressup', '0023_auto_20201120_2106'),
    ]

    operations = [
    ]
