# Generated by Django 3.1.3 on 2020-11-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0024_merge_20201124_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
