# Generated by Django 3.1.3 on 2020-11-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0025_remove_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='font_size',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
