# Generated by Django 3.1.3 on 2020-11-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0027_auto_20201124_1311'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Products',
        ),
    ]
