# Generated by Django 3.1.3 on 2020-11-25 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0028_auto_20201124_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='font_size',
        ),
    ]
